apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo-cash
  name: mongo-cash-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo-cash
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          hostPath:
                path: /data/mongodb/cash-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo-cash
  name: mongo-cash-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo-cash