apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service
        tier: backend
        track: stable
    spec:
      containers:
        - name: gateway-service
          image: "achalise/gateway-service:0.0.1"
          ports:
          - containerPort: 8080
          env:
            - name: CASH_SERVICE_HOST
              value: cash-service
            - name: CARD_SERVICE_HOST
              value: card-service
            - name: MONGO_URI
              value: mongo-gateway-service
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gateway-service
    tier: backend
  type: NodePort
