apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: card-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: card-service
        tier: backend
        track: stable
    spec:
      containers:
        - name: card-service
          image: "achalise/card-service:0.0.1"
          ports:
          - containerPort: 8080
          env:
            - name: MONGO_URI
              value: mongo-card-service
---
apiVersion: v1
kind: Service
metadata:
  name: card-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: card-service
    tier: backend

